export const MoviesData = [
    {
        name: "Avatar",
        desc: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        titleImage: "Avatar",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        category: "Action, Adventure, Fantasy",
        language: "English, Spanish",
        year: 2009,
        time: 3,
        video: '',
        rates: 1000,
        numberOfReviews: 200,
        rating: 7,
    },
    {
        name: "I Am Legend",
        desc: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        titleImage: "I Am Legend",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI0NTI4NjE3NV5BMl5BanBnXkFtZTYwMDA0Nzc4._V1_.jpg",
        category: "Drama, Horror, Sci-Fi",
        language: "English",
        year: 2011,
        time: 2,
        video: '',
        rates: 900,
        numberOfReviews: 300,
        rating: 9,
    },
    {
        name: "The Avengers",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "The Avengers",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0NjY0NzE4OTReQTJeQWpwZ15BbWU3MDczODg2Nzc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        category: "Action, Sci-Fi, Thriller",
        language: "English, Russian",
        year: 2001,
        time: 4,
        video: '',
        rates: 10000,
        numberOfReviews: 6000,
        rating: 10,
    },
    {
        name: "The Wolf of Wall Street",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "The Wolf of Wall Street",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BNDIwMDIxNzk3Ml5BMl5BanBnXkFtZTgwMTg0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        category: "Biography, Comedy, Crime",
        language: "English, French",
        year: 2013,
        time: 2,
        video: '',
        rates: 5000,
        numberOfReviews: 600,
        rating: 5,
    },
    {
        name: "Interstellar",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Interstellar",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NTEwOTMxMV5BMl5BanBnXkFtZTgwMjMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        category: "Adventure, Drama, Sci-Fi",
        language: "English",
        year: 2014,
        time: 3,
        video: '',
        rates: 650,
        numberOfReviews: 54,
        rating: 4,
    },
    {
        name: "Game of Thrones",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Game of Thrones",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BNDc1MGUyNzItNWRkOC00MjM1LWJjNjMtZTZlYWIxMGRmYzVlXkEyXkFqcGdeQXVyMzU3MDEyNjk@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        category: "Adventure, Drama, Fantasy",
        language: "English",
        year: 2004,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Vikings",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Vikings",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM5MTM1ODUxNV5BMl5BanBnXkFtZTgwNTAzOTI2ODE@._V1_.jpg",
        category: "Action, Drama, History",
        language: "English, Old English, Norse, Old, Latin",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Gotham",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Gotham",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BNDI3ODYyODY4OV5BMl5BanBnXkFtZTgwNjE5NDMwMDI@._V1_SY1000_SX1500_AL_.jpg",
        category: "Action, Crime, Drama",
        language: "English",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Power",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Power",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2ODg0MzMzM15BMl5BanBnXkFtZTgwODYxODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
        category: "Crime, Drama",
        language: "English",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Narcos",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Narcos",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2MDMzMTc0MF5BMl5BanBnXkFtZTgwMTAyMzA1OTE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        category: "Biography, Crime, Drama",
        language: "English, Spanish",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Breaking Bad",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Breaking Bad",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgyMzI5NDc5Nl5BMl5BanBnXkFtZTgwMjM0MTI2MDE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
        category: "Crime, Drama, Thriller",
        language: "English, Spanish",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Doctor Strange",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Doctor Strange",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3ODc1ODI5Ml5BMl5BanBnXkFtZTgwODMzMDY3OTE@._V1_.jpg",
        category: "Action, Adventure, Fantasy",
        language: "English",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    },
    {
        name: "Rogue One: A Star Wars Story",
        desc: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
        titleImage: "Rogue One: A Star Wars Story",
        image: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE3MzA4Nzk3NV5BMl5BanBnXkFtZTgwNjAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
        category: "Action, Adventure, Sci-Fi",
        language: "English",
        year: 2014,
        time: 3,
        video: '',
        rates: 540,
        numberOfReviews: 544,
        rating: 9,
    }
]
